steps:
  # ── 1. Build Docker image ────────────────────────────────────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gemini-web-navigator:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/gemini-web-navigator:latest'
      - '.'

  # ── 2. Push to Container Registry ───────────────────────────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gemini-web-navigator:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gemini-web-navigator:latest']

  # ── 3. Deploy to Cloud Run ───────────────────────────────────────────────────
  # Fix 5: --allow-unauthenticated makes the service publicly reachable.
  # GEMINI_API_KEY is injected at deploy time from Secret Manager
  # (secret name: gemini-api-key) so it is never stored in source or build logs.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gemini-web-navigator'
      - '--image=gcr.io/$PROJECT_ID/gemini-web-navigator:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'          # Fix 5: public access — no Google auth required
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--concurrency=10'
      # Fix 5: inject GEMINI_API_KEY from Secret Manager at deploy time
      - '--update-secrets=GEMINI_API_KEY=gemini-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/gemini-web-navigator:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/gemini-web-navigator:latest'

options:
  logging: CLOUD_LOGGING_ONLY
